server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
zuul:
  routes:
    customer:
      path: /customer-service/**
      serviceId: customer-service
    airline:
      path: /customer-service/**
      serviceId: customer-service